HolaMundoFramework/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HolaMundoFramework.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        public ActionResult Index()
        {
            ViewBag.Title = "Categorías";
            return View();
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.Title = "Crear Categoría";
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Editar Categoría";
            return View();
        }

        // POST: Categories/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Categories/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HolaMundoFramework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HolaMundoFramework.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HolaMundoFramework/Views/Categories/Create.cshtml
@Styles.Render("~/bundles/categoriesCSS")
<div class="card color-texto">
    <div class="container-fluid pad-top">
        <div><h4>Ingrese los datos:</h4></div>
        <hr>
        <form class="form-horizontal">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NombreCategoriaCrear" placeholder="Categoría">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 control-label">Descripción</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="DescripcionCategoriaCrear" placeholder="Descripción">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputCategorie" class="col-sm-2 control-label">Categoría Superior</label>
                <div class="col-sm-10">
                    <select id="CategoriaSuperiorCrear" class="form-control">
                        <option selected>Elegir</option>
                        <option>Evento</option>
                        <option>Lugar</option>
                        <option>Turista</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary pull-right">Agregar Categoría</button>
                </div>
            </div>
        </form>
    </div>
</div>

HolaMundoFramework/Views/Categories/Edit.cshtml
<div class="card color-texto">
    <div class="container-fluid pad-top">
        <h4>Ingrese los datos:</h4>
        <hr>
        <form class="form-horizontal">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 control-label">Categoría</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NombreCategoriaEditar" placeholder="Categoría">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 control-label">Descripción</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="DescripcionCategoriaEditar" placeholder="Editar descripción">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputCategorie" class="col-sm-2 control-label">Mover a la Categoría</label>
                <div class="col-sm-10">
                    <select id="CategoriaSuperiorEditar" class="form-control">
                        <option selected>Elegir</option>
                        <option>Evento</option>
                        <option>Lugar</option>
                        <option>Turista</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary pull-right">Editar Categoría</button>
                </div>
            </div>
        </form>

    </div>
</div>

HolaMundoFramework/Views/Categories/Index.cshtml
@Styles.Render("~/bundles/categoriesCSS")

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css ">


<div class="card">
    <div class="container-fluid pad-top">
        <div class="color-texto"><h4>Categoria principal</h4></div>
        <hr>
        <table width="100%" class="table table-striped table-bordered" id="example" cellspacing="0">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Opciones</th>
                    <th>Estatus</th>
                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>Lugar</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        <!--        <button type="button" class="btn btn-default circle" aria-label="Left Align">
                                <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                            </button> -->

                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Categories", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                    <td><input id="Checkbox1" type="checkbox" /> Activado</td>

                </tr>
                <tr>

                    <td>Evento</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        <!--       <button type="button" class="btn btn-default circle" aria-label="Left Align">
                               <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                           </button>  -->
                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Categories", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                    <td><input id="Checkbox1" type="checkbox" /> Activado</td>

                </tr>
                <tr>

                    <td>Turistas</td>
                    <td>lorem ipsum</td>
                    <td>
                        <button type="button" class="btn btn-default circle" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Listar subcategorias">
                            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-default circle ver-categoria" aria-label="Left Align" data-toggle="tooltip" data-placement="top"
                                title="Ver mas">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                        <!--        <button type="button" class="btn btn-default circle" aria-label="Left Align">
                                <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                            </button> -->
                        <a class="btn btn-default circle" href="@Url.Action("Edit", "Categories", new { id = 1 })" data-toggle="tooltip"
                           data-placement="top" title="Editar">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>

                    </td>
                    <td><input id="Checkbox1" type="checkbox" /> Activado</td>

                </tr>
            </tbody>
        </table>
    </div>
    
</div>


<!--MODAL-->

<div class="modal fade" id="mostrarCategoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Detalles de la categoria</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="nombre" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" id="nombre" value="Evento" readonly>
                    </div>
                    <div class="form-group">
                        <label for="descripcion" class="col-form-label">Descripcion:</label>
                        <textarea class="form-control" id="descripcion" readonly>Base sobre la cual surgiran la categorias</textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>



@section scripts {
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js "></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/categoriesJS")
    
    }

HolaMundoFramework/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HolaMundoFramework/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HolaMundoFramework/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HolaMundoFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="@Url.Content("~/Images/logo_cocotrip.png")"  />
    <title>@ViewBag.Title - COCOTRIP</title>

    <!-- GOOGLE FONTS -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>



    <div id="wrapper">

        <div class="container-fluid">
            <div class="row">
                <div class="col-3">
                    <!-- /. NAV TOP  -->
                    <nav class="navbar-default navbar-side" role="navigation">
                        <div class="sidebar-collapse">
                            <ul class="nav" id="main-menu">

                                <div class="logo-sidebar" align="center">
                                    <img src="@Url.Content("~/Images/logo_sidebar.png")" alt="">
                                </div>

                                <li class="active">
                                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-desktop "></i>Dashboard</a>         
                                </li>

                                <li data-toggle="collapse" data-target="#products" class="collapsed active">
                                    <a href="#"><i class="fa fa-map-o" aria-hidden="true"></i> Lugar Turístico <span class="arrow"></span></a>
                                </li>
                                <ul class="sub-menu collapse" id="products">
                                    <li class="active"><a href="#"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Todos</a></li>
                                    <li><a href="#"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                                </ul>
                                <li data-toggle="collapse" data-target="#categoriesOption" class="collapsed active">
                                    <a  href="#"><i class="fa fa-desktop"  aria-hidden="true"></i>Categorías</a>
                                </li>
                                <ul class="sub-menu collapse sideItem" id="categoriesOption">
                                    <li><a href="@Url.Action("Create", "Categories")"><i class="fa fa-plus icon-add-sidebar" aria-hidden="true"></i>Agregar</a></li>
                                    <li class="active"><a href="@Url.Action("Index", "Categories")"><i class="fa fa-eye icon-see-sidebar" aria-hidden="true"></i>Ver Categorías</a></li>
                                </ul>
                            </ul>
                        </div>

                    </nav>
                    <!-- /. NAV SIDE  -->
                </div>

                <div class="col-9">
                    <div id="page-wrapper">
                        <div id="page-inner">

                            <div class="content-page">
                                <div class="row">
                                    <div class="headline card">
                                        <h4 class="tittle">
                                            @ViewBag.Title
                                        </h4>
                                    </div>
                                </div>
                                <!-- aqui -->
                                <div class="row" style="margin-top: 5%;">
                                    <!-- o aqui -->
                                    @RenderBody()
                                </div>
                            </div>

                        </div>
                        <!-- /. PAGE INNER  -->
                    </div>
                    <!-- /. PAGE WRAPPER  -->
                </div>

            </div>
        </div>

    </div>
    <div class="footer">
        <div class="row">
            <div class="col-lg-12">
                &copy; @DateTime.Now.Year - Mi aplicación ASP.NET
            </div>
        </div>
    </div>






    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/customJS")
    @RenderSection("scripts", required: false)


</body>

</html>